#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/theme-lib.sh"

KVANTUM_CONFIG_DIR="$HOME/.config/Kvantum"
KVANTUM_CONF_FILE="$KVANTUM_CONFIG_DIR/kvantum.kvconfig"
GTK3_CONFIG="$HOME/.config/gtk-3.0"
GTK4_CONFIG="$HOME/.config/gtk-4.0"
QT5CT_CONFIG="$HOME/.config/qt5ct"
QT6CT_CONFIG="$HOME/.config/qt6ct"
GTKRC2="$HOME/.gtkrc-2.0"

show_help() {
    cat <<'EOF'
theme-unifier.sh apply|status|reset|help
EOF
}

detect_qt_platformtheme() {
    local -a qt6_plugins=(
        "/usr/lib/qt6/plugins/platformthemes/libqt6ct.so"
        "/usr/lib/qt6/plugins/platformthemes/qt6ct.so"
        "/usr/lib/qt6/plugins/platformthemes/libqt6ct.so.1"
    )
    local -a qt5_plugins=(
        "/usr/lib/qt/plugins/platformthemes/libqt5ct.so"
        "/usr/lib/qt/plugins/platformthemes/qt5ct.so"
        "/usr/lib/qt5/plugins/platformthemes/libqt5ct.so"
        "/usr/lib/qt5/plugins/platformthemes/qt5ct.so"
        "/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqt5ct.so"
    )
    local -a gtk3_plugins=(
        "/usr/lib/qt6/plugins/platformthemes/libqgtk3.so"
        "/usr/lib/qt6/plugins/platformthemes/qgtk3.so"
        "/usr/lib/qt/plugins/platformthemes/libqgtk3.so"
        "/usr/lib/qt/plugins/platformthemes/qgtk3.so"
        "/usr/lib/qt5/plugins/platformthemes/libqgtk3.so"
        "/usr/lib/qt5/plugins/platformthemes/qgtk3.so"
        "/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so"
    )
    local plugin

    for plugin in "${qt6_plugins[@]}"; do
        [[ -f "$plugin" ]] && { echo "qt6ct"; return 0; }
    done
    for plugin in "${qt5_plugins[@]}"; do
        [[ -f "$plugin" ]] && { echo "qt5ct"; return 0; }
    done
    for plugin in "${gtk3_plugins[@]}"; do
        [[ -f "$plugin" ]] && { echo "gtk3"; return 0; }
    done
}

detect_qt_style_override() {
    local -a kvantum_plugins=(
        "/usr/lib/qt6/plugins/styles/libkvantum.so"
        "/usr/lib/qt6/plugins/styles/kvantum.so"
        "/usr/lib/qt/plugins/styles/libkvantum.so"
        "/usr/lib/qt/plugins/styles/kvantum.so"
        "/usr/lib/qt5/plugins/styles/libkvantum.so"
        "/usr/lib/qt5/plugins/styles/kvantum.so"
    )
    local -a breeze_plugins=(
        "/usr/lib/qt6/plugins/styles/breeze6.so"
        "/usr/lib/qt/plugins/styles/breeze.so"
    )
    local plugin

    for plugin in "${kvantum_plugins[@]}"; do
        [[ -f "$plugin" ]] && { echo "kvantum"; return 0; }
    done
    for plugin in "${breeze_plugins[@]}"; do
        [[ -f "$plugin" ]] && { echo "breeze"; return 0; }
    done
}

ensure_kvantum_theme() {
    local kvantum_theme="/usr/share/Kvantum/Sweet/Sweet.kvconfig"

    [[ -f "$kvantum_theme" ]] || return 0

    mkdir -p "$KVANTUM_CONFIG_DIR"
    cat > "$KVANTUM_CONF_FILE" <<EOF
[General]
theme=Sweet
EOF
}

write_hypr_env_conf() {
    local platformtheme=""
    local style_override=""

    mkdir -p "$(dirname "$HYPR_THEME_ENV_CONF")"
    platformtheme="$(detect_qt_platformtheme || true)"
    style_override="$(detect_qt_style_override || true)"

    if [[ "$style_override" == "kvantum" ]]; then
        ensure_kvantum_theme
    fi

    {
        echo "# Generated by ~/.config/hypr/scripts/system/theme-unifier.sh"
        echo "env = XCURSOR_THEME,$CURSOR_THEME"
        echo "env = QT_CURSOR_THEME,$CURSOR_THEME"
        echo "env = HYPRCURSOR_THEME,$CURSOR_THEME"
        echo "envd = XCURSOR_SIZE,$CURSOR_SIZE"
        echo "envd = QT_CURSOR_SIZE,$CURSOR_SIZE"
        echo "envd = HYPRCURSOR_SIZE,$CURSOR_SIZE"
        if [[ -n "$platformtheme" ]]; then
            echo "env = QT_QPA_PLATFORMTHEME,$platformtheme"
        fi
        if [[ -n "$style_override" ]]; then
            echo "env = QT_STYLE_OVERRIDE,$style_override"
        fi
    } > "$HYPR_THEME_ENV_CONF"
}

create_gtk_configs() {
    mkdir -p "$GTK3_CONFIG" "$GTK4_CONFIG"

    cat > "$GTK3_CONFIG/settings.ini" <<EOF
[Settings]
gtk-theme-name=$GTK_THEME
gtk-icon-theme-name=$ICON_THEME
gtk-cursor-theme-name=$CURSOR_THEME
gtk-cursor-theme-size=$CURSOR_SIZE
gtk-font-name=Cantarell 11
gtk-application-prefer-dark-theme=true
gtk-decoration-layout=:minimize,maximize,close
gtk-enable-animations=true
gtk-primary-button-warps-slider=false
EOF

    cat > "$GTK4_CONFIG/settings.ini" <<EOF
[Settings]
gtk-theme-name=$GTK_THEME
gtk-icon-theme-name=$ICON_THEME
gtk-cursor-theme-name=$CURSOR_THEME
gtk-cursor-theme-size=$CURSOR_SIZE
gtk-font-name=Cantarell 11
gtk-application-prefer-dark-theme=true
gtk-decoration-layout=:minimize,maximize,close
gtk-enable-animations=true
gtk-primary-button-warps-slider=false
EOF

    cat > "$GTKRC2" <<EOF
gtk-theme-name="$GTK_THEME"
gtk-icon-theme-name="$ICON_THEME"
gtk-cursor-theme-name="$CURSOR_THEME"
gtk-cursor-theme-size=$CURSOR_SIZE
gtk-font-name="Cantarell 11"
EOF
}

create_qt_configs() {
    local qt_style=""

    qt_style="$(detect_qt_style_override || true)"
    [[ -n "$qt_style" ]] || qt_style="gtk2"

    mkdir -p "$QT5CT_CONFIG" "$QT6CT_CONFIG"

    cat > "$QT5CT_CONFIG/qt5ct.conf" <<EOF
[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=$ICON_THEME
standard_dialogs=gtk3
style=$qt_style

[Fonts]
fixed=Noto Sans Mono,10,-1,5,50,0,0,0,0,0
general=Noto Sans,10,-1,5,50,0,0,0,0,0

[Interface]
activate_item_on_single_click=1
buttonbox_layout=3
cursor_flash_time=1000
dialog_buttons_have_icons=2
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[SettingsWindow]
geometry=@ByteArray()

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
EOF

    cat > "$QT6CT_CONFIG/qt6ct.conf" <<EOF
[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=$ICON_THEME
standard_dialogs=gtk3
style=$qt_style

[Fonts]
fixed=Noto Sans Mono,10,-1,5,50,0,0,0,0,0
general=Noto Sans,10,-1,5,50,0,0,0,0,0

[Interface]
activate_item_on_single_click=1
buttonbox_layout=3
cursor_flash_time=1000
dialog_buttons_have_icons=2
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[SettingsWindow]
geometry=@ByteArray()

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
EOF
}

apply_gsettings() {
    command -v gsettings >/dev/null 2>&1 || return 0

    gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
    gsettings set org.gnome.desktop.interface icon-theme "$ICON_THEME"
    gsettings set org.gnome.desktop.interface cursor-theme "$CURSOR_THEME"
    gsettings set org.gnome.desktop.interface cursor-size "$CURSOR_SIZE"
    gsettings set org.gnome.desktop.interface font-name "Cantarell 11"
    gsettings set org.gnome.desktop.interface monospace-font-name "Monospace 10"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
    gsettings set org.gnome.desktop.interface enable-animations true
}

apply_runtime_hypr_env() {
    command -v hyprctl >/dev/null 2>&1 || return 0
    [[ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]] || return 0

    hyprctl keyword env "XCURSOR_THEME,$CURSOR_THEME" >/dev/null 2>&1 || true
    hyprctl keyword env "QT_CURSOR_THEME,$CURSOR_THEME" >/dev/null 2>&1 || true
    hyprctl keyword env "HYPRCURSOR_THEME,$CURSOR_THEME" >/dev/null 2>&1 || true
    hyprctl keyword env "XCURSOR_SIZE,$CURSOR_SIZE" >/dev/null 2>&1 || true
    hyprctl keyword env "QT_CURSOR_SIZE,$CURSOR_SIZE" >/dev/null 2>&1 || true
    hyprctl keyword env "HYPRCURSOR_SIZE,$CURSOR_SIZE" >/dev/null 2>&1 || true
}

apply_theme() {
    load_theme_state
    create_gtk_configs
    create_qt_configs
    apply_gsettings
    write_hypr_env_conf
    apply_runtime_hypr_env
}

show_status() {
    local platformtheme=""
    local style_override=""

    load_theme_state
    platformtheme="$(detect_qt_platformtheme || true)"
    style_override="$(detect_qt_style_override || true)"

    cat <<EOF
Theme state file: $THEME_STATE_FILE
Hypr env file: $HYPR_THEME_ENV_CONF
GTK_THEME=$GTK_THEME
ICON_THEME=$ICON_THEME
CURSOR_THEME=$CURSOR_THEME
CURSOR_SIZE=$CURSOR_SIZE
QT_QPA_PLATFORMTHEME=${platformtheme:-unset}
QT_STYLE_OVERRIDE=${style_override:-unset}
EOF
}

reset_theme() {
    save_theme_state \
        "$THEME_DEFAULT_GTK" \
        "$THEME_DEFAULT_ICONS" \
        "$THEME_DEFAULT_CURSOR" \
        "$THEME_DEFAULT_CURSOR_SIZE"
    apply_theme
}

case "${1:-apply}" in
    apply)
        apply_theme
        ;;
    status)
        show_status
        ;;
    reset)
        reset_theme
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        show_help
        exit 1
        ;;
esac
