# Bloquear la pantalla con hyprlock al cerrar la tapa
bindl=,switch:on:Lid Switch,exec,hyprlock --immediate && systemctl suspend

# █▀▀ █▀█ █▀█ █▀▀ █▀ █▀▀ █▀█ █▀█ █▀ █▀▀ █▀
# █▄▄ █▄█ █▀▄ ██▄ ▄█ █▄▄ █▀▄ █▄█ ▄█ ██▄ ▄█

# Core Variables
# Modifier keys
$mainMod = SUPER
$altMod = ALT
$ctrlMod = CTRL
$shiftMod = SHIFT

# Scripts and utilities
#$screenshot = ~/.config/hypr/scripts/screenshot.sh
#$colorpicker = ~/.config/hypr/scripts/colorpicker.sh
#$volume = ~/.config/hypr/scripts/volume.sh
#$brightness = ~/.config/hypr/scripts/brightness.sh

# Paths
$wallpapers = ~/Wallpapers
$screenshots = ~/Pictures/Screenshots

# Display
$gaps = 4
$border = 2
$radius = 8

# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀ █▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄ ▄█

# Configuration Files
# Load configuration files
source = config/*
# Load theme
source = themes/colors/default.conf

