# █▀▀ █▀█ █▀█ █▀▀ █▀ █▀▀ █▀█ █▀█ █▀ █▀▀ █▀
# █▄▄ █▄█ █▀▄ ██▄ ▄█ █▄▄ █▀▄ █▄█ ▄█ ██▄ ▄█

# Core Variables
# Modifier keys
$mainMod = SUPER
$altMod = ALT
$ctrlMod = CTRL
$shiftMod = SHIFT

# Paths
$wallpapers = ~/Wallpapers
$screenshots = ~/Pictures/Screenshots

# Bloquear la pantalla con hyprlock al cerrar la tapa
bindl=,switch:on:Lid Switch,exec,~/.config/hypr/scripts/system/lock.sh ; systemctl suspend

# █▀ █▀█ █░█ █▀█ █▀▀ █▀▀ █▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄ ▄█

# Configuration Files

# Load theme
source = themes/colors/default.conf
# Load configuration files
source = config/*
