# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$idlehandler = ~/.config/hypr/scripts/system/idle-config.sh
$lockCmd = ~/.config/hypr/scripts/system/lock.sh
$sttCmd = ~/.config/hypr/scripts/system/transcribirAudio/stt.sh
$themeManager = ~/.config/hypr/scripts/system/theme-manager.sh
$wallpaperControl = ~/.config/hypr/scripts/tools/wallpaper-control.sh
$terminal = kitty
$fileManager = thunar
$menu = fuzzel
$code = code
$browser = zen
$rofiUtils = /home/shidox/.config/rofi/scripts/
$launcher = $rofiUtils/allApps
