# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$idlehandler = ~/.config/hypr/scripts/system/idle-config.sh
$terminal = kitty
$fileManager = thunar
$menu = fuzzel
$code = code
$browser = zen
$rofiUtils = $HOME/.config/hypr/rofi/scripts/utilities
$launcher = $rofiUtils/allApps