# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                  Application Variables (env)                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# These variables are exported to the environment for exec commands

env = TERM,xterm-256color
env = TERMINAL,kitty
env = EDITOR,nano

# Applications
env = APP_TERMINAL,kitty
env = APP_FILEMANAGER,thunar
env = APP_MENU,fuzzel
env = APP_CODE,code
env = APP_BROWSER,zen
