# █▀▀ █▄░█ █░█ █ █▀█ █▀█ █▄░█ █▀▄▀█ █▀▀ █▄░█ ▀█▀
# █▀░ █░▀█ ▀▄▀ █ █▀▄ █▄█ █░▀█ █░▀░█ ██▄ █░▀█ ░█░
# Environment Variables

# Qt/GTK Theme Configuration
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
#env = QT_STYLE_OVERRIDE,Sweet-Dark

# GTK Theme Configuration
env = GDK_BACKEND,wayland,x11
#env = GTK_THEME,Sweet-Dark
env = GTK_USE_PORTAL,1

# XDG
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Hardware video acceleration
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm

# Nvidia specific
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVIDIA_PRESERVE_VIDEO_MEMORY_ALLOCATIONS,1
env = WLR_NO_HARDWARE_CURSORS,0
env = WLR_DRM_NO_ATOMIC,1

envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24

# Cursor theme configuration
env = HYPRCURSOR_THEME,Sweet-cursors
env = XCURSOR_THEME,Sweet-cursors
env = QT_CURSOR_THEME,Sweet-cursors



# Forzamos a las aplicaciones SDL a usar el backend de Wayland
env = SDL_VIDEODRIVER,wayland

# Aplicaciones específicas para Wayland
env = MOZ_ENABLE_WAYLAND,1
env = MOZ_WEBRENDER,1
env = CLUTTER_BACKEND,wayland
env = BEMENU_BACKEND,wayland

# Optimización de rendimiento
env = __GL_SHADER_DISK_CACHE,1
env = __GL_SHADER_DISK_CACHE_PATH,/tmp
