# █▀▄ █▀▀ █▀▀ █▀█ █▀█ ▄▀█ ▀█▀ █ █▀█ █▄░█
# █▄▀ ██▄ █▄▄ █▄█ █▀▄ █▀█ ░█░ █ █▄█ █░▀█

decoration {
  rounding = 14

  blur {
    enabled            = true
    size               = 6
    passes             = 2
    new_optimizations  = true
    ignore_opacity     = true
    popups             = true    # incluye layer-shell popups
    popups_ignorealpha = 0.3     # si tu Rofi usa transparencia parcial
    xray               = false
    vibrancy           = 0.1
    vibrancy_darkness  = 0.8
    ##contrast = 0.5
    special            = true
  }



    # Shadow Effect
    #drop_shadow = true
    #shadow_range = 8
    #shadow_render_power = 2
    #col.shadow = rgba(00000044)
    #shadow_offset = 2 2

    # Active/Inactive Opacity
    #active_opacity = 1
    inactive_opacity = 1

    # Window Dimming
    dim_inactive = false
    dim_strength = 0.1
}


