# █░█ █▀▀ █░░ █▀█ █▀▀ █▄░█ █░█ █▀▄▀█ █▀▀ █▄░█ ▀█▀
# █▄█ █▄▄ █▄▄ █▄█ █▄▄ █░▀█ ▀▄▀ █░▀░█ ██▄ █░▀█ ░█░
# Configuración de Workspaces

# Workspaces principales en monitor principal
workspace = 1, monitor:DP-1, default:true, persistent:false
workspace = 2, monitor:DP-1, persistent:false
workspace = 3, monitor:DP-1, persistent:false
workspace = 4, monitor:DP-1, persistent:false
workspace = 5, monitor:DP-1, persistent:false
workspace = 6, monitor:DP-1, persistent:false
workspace = 7, monitor:DP-1, persistent:false
