# ============================================================================
# Layer and global rules
# ============================================================================

layerrule = blur on, match:namespace rofi|dunst|swaync
layerrule = ignore_alpha 0.0, match:namespace rofi|dunst|swaync
layerrule = dim_around on, match:namespace rofi|dunst|swaync
layerrule = animation popin, match:namespace rofi|dunst|swaync

layerrule = blur on, match:namespace qs_.*
layerrule = ignore_alpha 0.0, match:namespace qs_.*
layerrule = animation popin, match:namespace qs_.*

layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.3, match:namespace swaync-control-center
layerrule = animation popin, match:namespace swaync-control-center

windowrule {
    name = Global No Initial Focus
    match:class = .*
    suppress_event = maximize
}
