# Launch favorite apps 
exec-once = ~/.config/hypr/scripts/tools/wallpaper-control.sh change --pywal
# Theme unification (cursor + Qt/GTK themes)
exec-once = ~/.config/hypr/scripts/system/theme-unifier.sh apply

# Core components for system functionality

exec-once = gnome-keyring-daemon --start --components=secrets,ssh  #Authentication
exec-once = ~/.config/hypr/scripts/system/polkit-agent.sh  #Authentication agent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE # Update dbus environment
exec-once = udiskie  # Automount disks
exec-once = /usr/lib/geoclue-2.0/demos/agent 
exec-once = xsettingsd # XSettings daemon for GTK theme support
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
# Idle configuration
exec-once = ~/.config/hypr/scripts/system/idle-config.sh 

# XDG Portal setup
exec-once = ~/.config/hypr/scripts/system/xdgportal.sh 

# bar
exec-once = systemctl --user import-environment PATH WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORM && sleep 1 && ~/.config/hypr/scripts/start-quickshell.sh
exec-once = systemctl --user import-environment PATH WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QTA_PLATFORM && sleep 1 && swww-daemon
