#!/usr/bin/env bash

DIR="$HOME/.config/hypr"
LOCK_CMD="$DIR/scripts/system/lock.sh"
ROFI_THEME="$DIR/rofi/themes/powermenu.rasi"
ASKPASS_THEME="$DIR/rofi/themes/askpass.rasi"
CONFIRM_CMD="$DIR/rofi/scripts/utilities/confirm"

uptime=$(uptime -p | sed -e 's/up //g')

shutdown=""
reboot=""
lock=""
suspend=""
logout=""

options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"
invalid_msg="Options - yes / y / no / n"

ask_confirmation() {
    local answer

    answer=$("$CONFIRM_CMD")
    case "${answer,,}" in
        yes|y) return 0 ;;
        no|n) return 1 ;;
        *)
            rofi -theme "$ASKPASS_THEME" -e "$invalid_msg"
            return 2
            ;;
    esac
}

run_power_action() {
    case "$1" in
        shutdown)
            systemctl poweroff
            ;;
        reboot)
            systemctl reboot
            ;;
        lock)
            "$LOCK_CMD"
            ;;
        suspend)
            "$LOCK_CMD" &
            sleep 0.5
            systemctl suspend
            ;;
        logout)
            hyprctl dispatch exit
            ;;
    esac
}

chosen=$(echo -e "$options" | rofi -theme "$ROFI_THEME" -p "UP - $uptime" -dmenu)

case "$chosen" in
    "$shutdown")
        if ask_confirmation; then
            run_power_action shutdown
        fi
        ;;
    "$reboot")
        if ask_confirmation; then
            run_power_action reboot
        fi
        ;;
    "$lock")
        run_power_action lock
        ;;
    "$suspend")
        if ask_confirmation; then
            run_power_action suspend
        fi
        ;;
    "$logout")
        if ask_confirmation; then
            run_power_action logout
        fi
        ;;
esac
